### PR TITLE
Added interpolation option to the command line utility to match core

### PR DESCRIPTION
**Pull request by nightwatchcyber**
…rkup-core

### CODE REVIEW

**Comment by bkabrda** [comment]
The change looks good, but I'd like to ask you to add help to the new argument. When that's done, I'll merge.

**Comment by nightwatchcyber** [comment]
@bkabrda Oops, sorry about that. I updated the pull request with the help on the new option.

Thanks!

**Comment by bkabrda** [comment]
LGTM, merging. Thanks!

**Comment by bkabrda** [comment]
Released: https://pypi.org/project/anymarkup/0.8.1/

**Pull request merged**
